### ISSUE TITLE
【bug】最新版本father-build打包报错，回退到1.20.1没有问题

### ISSUE THREAD

**Issue by mctl** [umijs/father#428] opened 2021-11-11 02:31 UTC
目测是这两天的版本存在问题，报错内容与楼上类似：

$ father-build
Clean dist directory
Build cjs with babel
Clean lib directory
error TS5023: Unknown compiler option 'cwd'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
/home/jenkins/agent/workspace/aps_bugfix_rocket_6.1.0/node_modules/@gulp-plugin/alias/lib/index.js:17
    return file.flatMap((line, index) => findImports(line).map((i) => ({ path: dir, index, import: i })));
                ^

TypeError: file.flatMap is not a function
    at parseImports (/home/jenkins/agent/workspace/aps_bugfix_rocket_6.1.0/node_modules/@gulp-plugin/alias/src/index.ts:31:15)
    at Transform.transform [as _transform] (/home/jenkins/agent/workspace/aps_bugfix_rocket_6.1.0/node_modules/@gulp-plugin/alias/src/index.ts:165:23)
    at Transform._read (_stream_transform.js:190:10)
    at Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Transform.Writable.write (_stream_writable.js:294:11)
    at Readable.ondata (_stream_readable.js:689:20)
    at Readable.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
error Command failed with exit code 1.

目前通过写死1.20.1版本解决问题，希望尽快解决一下～～

**Comment by PeachScript** [comment] 2021-11-11 02:42
Duplicate of #427

**Closed by PeachScript** 2021-11-11 02:42 UTC
